(deftheme coffee
  "A simple theme on your eyes.")

(custom-theme-set-faces 'coffee
 '(default ((t (:foreground "#fdf4c1" :background "#282828" ))))
 '(cursor ((t (:background "#fdf4c1" ))))
 '(fringe ((t (:background "#282828" ))))
 '(region ((t (:background "#2d449e" ))))
 '(secondary-selection ((t (:background "#3e3834" ))))
 '(font-lock-builtin-face ((t (:foreground "#84a341" ))))
 '(font-lock-comment-face ((t (:foreground "#a38f7d"))))
 '(font-lock-function-name-face ((t (:foreground "#a99865" ))))
 '(font-lock-keyword-face ((t (:foreground "#db963d" ))))
 '(font-lock-string-face ((t (:foreground "#6d7c5d" ))))
 '(font-lock-type-face ((t (:foreground "#af9849" ))))
 '(font-lock-constant-face ((t (:foreground "#bbaa97" ))))
 '(font-lock-variable-name-face ((t (:foreground "#abb780" ))))
 '(minibuffer-prompt ((t (:foreground "#cea03d" :bold t ))))
 '(font-lock-warning-face ((t (:foreground "red" :bold t ))))
 '(mode-line ((t (:foreground "#ece09f" :background "#383634"))))
 '(mode-line-inactive ((t (:inherit mode-line :background "#282828" :foreground "gray40" :weight light))))
 '(company-echo-common ((t (:foreground "gold"))))
 '(company-preview ((t (:background "gray18" :foreground "wheat"))))
 '(company-preview-common ((t (:inherit company-preview :foreground "gold"))))
 '(company-scrollbar-bg ((t (:background "c6c3b4"))))
 '(company-scrollbar-fg ((t (:background "7f7d69"))))
 '(company-tooltip ((t (:background "#353535" :foreground "white"))))
 '(company-tooltip-annotation ((t (:foreground "gray"))))
 '(company-tooltip-selection ((t (:background "gray50"))))
 '(helm-candidate-number ((t (:extend t :background "gray40" :foreground "black"))))
 '(helm-source-header ((t (:extend t :background "gray10" :foreground "white" :weight bold :height 1.3 :family "Sans Serif"))))
 '(helm-swoop-target-line-face ((t (:background "gray25" :foreground "#fdf4c1")))) ; Remove these two if you don't have helm-swoop.
 '(helm-swoop-target-word-face ((t (:background "NavajoWhite4" :foreground "#ffffff")))) ; ^
 '(highlight ((t (:background "#2f3813"))))
 '(link ((t (:foreground "gray65" :underline t))))
 '(anzu-mode-line ((t (:foreground "cornflower blue" :weight bold))))
 '(company-echo-common ((t (:foreground "gold"))))
 '(company-preview ((t (:background "gray18" :foreground "wheat"))))
 '(company-preview-common ((t (:inherit company-preview :foreground "gold"))))
 '(company-scrollbar-bg ((t (:background "black"))))
 '(company-scrollbar-fg ((t (:background "lemon chiffon"))))
 '(company-tooltip ((t (:background "#353535" :foreground "white"))))
 '(company-tooltip-annotation ((t (:foreground "gray"))))
 '(company-tooltip-common ((t (:foreground "gold"))))
 '(company-tooltip-common-selection ((t (:inherit wheat))))
 '(company-tooltip-selection ((t (:background "gray30"))))
 '(helm-bookmark-addressbook ((t (:extend t :foreground "tomato"))))
 '(helm-buffer-directory ((t (:extend t :background "gray20" :foreground "white"))))
 '(helm-buffer-file ((t (:foreground "white"))))
 '(helm-buffer-process ((t (:extend t :foreground "gray40"))))
 '(helm-buffer-size ((t (:extend t :foreground "dim gray"))))
 '(helm-candidate-number ((t (:extend t :background "gray40" :foreground "black"))))
 '(helm-ff-directory ((t (:extend t :background "gray20" :foreground "white"))))
 '(helm-ff-dirs ((t (:background "gray20" :foreground "ivory"))))
 '(helm-ff-dotted-directory ((t (:extend t :background "gray20" :foreground "ivory" :box (:line-width (1 . 1) :color "grey35")))))
 '(helm-ff-executable ((t (:extend t :foreground "lemon chiffon"))))
 '(helm-ff-file ((t (:extend t :foreground "gray"))))
 '(helm-ff-file-extension ((t (:extend t :foreground "gray90"))))
 '(helm-selection ((t (:extend t :background "#404040" :distant-foreground "black"))))
 '(helm-source-header ((t (:extend t :background "gray10" :foreground "white" :weight bold :height 1.3 :family "Sans Serif"))))
 '(helm-swoop-target-line-face ((t (:background "gray25" :foreground "#fdf4c1"))))
 '(helm-swoop-target-word-face ((t (:background "NavajoWhite4" :foreground "#ffffff"))))
 '(highlight ((t (:background "gray20"))))
 '(ido-only-match ((t (:foreground "green"))))
 '(ido-subdir ((t (:foreground "burlywood"))))
 '(ivy-current-match ((t (:extend t :background "seashell4" :foreground "black"))))
 '(link ((t (:foreground "gray65" :underline t))))
 '(minibuffer-prompt ((t (:foreground "#cea03d" :weight normal))))
 '(scroll-bar ((t (:foreground "black"))))
 '(selectrum-current-candidate ((t (:extend t :background "gray30"))))
)

(provide-theme 'coffee)
