(deftheme Graham Modified
  "Created 2022-01-19.")

(custom-theme-set-faces
 'Graham Modified
 '(default ((t (:family "Liberation Mono" :foundry "outline" :width normal :height 102 :weight normal :slant normal :underline nil :overline nil :extend nil :strike-through nil :box nil :inverse-video nil :foreground "#DEDEDE" :background "#161A1F" :stipple nil :inherit nil))))
 '(cursor ((t (:background "#FFFAAA"))))
 '(fixed-pitch ((t (:family "Monospace"))))
 '(variable-pitch ((((type w32)) (:foundry "outline" :family "Arial")) (t (:family "Sans Serif"))))
 '(escape-glyph ((((background dark)) (:foreground "cyan")) (((type pc)) (:foreground "magenta")) (t (:foreground "brown"))))
 '(homoglyph ((((background dark)) (:foreground "cyan")) (((type pc)) (:foreground "magenta")) (t (:foreground "brown"))))
 '(minibuffer-prompt ((t (:foreground "#C6C5FE"))))
 '(highlight ((t (:background "#151515"))))
 '(region ((t (:extend t :background "#1D1F21"))))
 '(shadow ((((class color grayscale) (min-colors 88) (background light)) (:foreground "grey50")) (((class color grayscale) (min-colors 88) (background dark)) (:foreground "grey70")) (((class color) (min-colors 8) (background light)) (:foreground "green")) (((class color) (min-colors 8) (background dark)) (:foreground "yellow"))))
 '(secondary-selection ((((class color) (min-colors 88) (background light)) (:extend t :background "yellow1")) (((class color) (min-colors 88) (background dark)) (:extend t :background "SkyBlue4")) (((class color) (min-colors 16) (background light)) (:extend t :background "yellow")) (((class color) (min-colors 16) (background dark)) (:extend t :background "SkyBlue4")) (((class color) (min-colors 8)) (:extend t :foreground "black" :background "cyan")) (t (:inverse-video t))))
 '(trailing-whitespace ((((class color) (background light)) (:background "red1")) (((class color) (background dark)) (:background "red1")) (t (:inverse-video t))))
 '(font-lock-builtin-face ((t (:foreground "#F38630"))))
 '(font-lock-comment-delimiter-face ((t (:foreground "gray75"))))
 '(font-lock-comment-face ((t (:foreground "gray75"))))
 '(font-lock-constant-face ((t (:foreground "#F38630"))))
 '(font-lock-doc-face ((t (:foreground "#615953"))))
 '(font-lock-function-name-face ((t (:foreground "#FFD2A7"))))
 '(font-lock-keyword-face ((t (:foreground "#FFA927"))))
 '(font-lock-negation-char-face ((t (:foreground "#FF6C60"))))
 '(font-lock-preprocessor-face ((t (:foreground "#FFA927"))))
 '(font-lock-regexp-grouping-backslash ((t (:foreground "#E9C"))))
 '(font-lock-regexp-grouping-construct ((t (:foreground "#E9C"))))
 '(font-lock-string-face ((t (:foreground "#615953"))))
 '(font-lock-type-face ((t (:foreground "#F38630"))))
 '(font-lock-variable-name-face ((t (:foreground "#C6C5FE"))))
 '(font-lock-warning-face ((t (:foreground "#FF6C60"))))
 '(button ((t (:underline (:color foreground-color :style line) :foreground "#FFA927"))))
 '(link ((((class color) (min-colors 88) (background light)) (:underline (:color foreground-color :style line) :foreground "RoyalBlue3")) (((class color) (background light)) (:underline (:color foreground-color :style line) :foreground "blue")) (((class color) (min-colors 88) (background dark)) (:underline (:color foreground-color :style line) :foreground "cyan1")) (((class color) (background dark)) (:underline (:color foreground-color :style line) :foreground "cyan")) (t (:inherit (underline)))))
 '(link-visited ((default (:inherit (link))) (((class color) (background light)) (:foreground "magenta4")) (((class color) (background dark)) (:foreground "violet"))))
 '(fringe ((t (:background "#161A1F"))))
 '(header-line ((t (:foreground "#DEDEDE" :background "#CCCCCC"))))
 '(tooltip ((((class color)) (:inherit (variable-pitch) :foreground "black" :background "lightyellow")) (t (:inherit (variable-pitch)))))
 '(mode-line ((t (:foreground "#333333" :background "#CCCCCC"))))
 '(mode-line-buffer-id ((t (:weight bold))))
 '(mode-line-emphasis ((t (:weight bold))))
 '(mode-line-highlight ((((class color) (min-colors 88)) (:box (:line-width 2 :color "grey40" :style released-button))) (t (:inherit (highlight)))))
 '(mode-line-inactive ((t (:foreground "#FFF" :background "#222"))))
 '(isearch ((t (:foreground "#1D1F21" :background "#E9C"))))
 '(isearch-fail ((t (:background "#FF6C60"))))
 '(lazy-highlight ((t (:foreground "#1D1F21" :background "#F38630"))))
 '(match ((((class color) (min-colors 88) (background light)) (:background "yellow1")) (((class color) (min-colors 88) (background dark)) (:background "RoyalBlue3")) (((class color) (min-colors 8) (background light)) (:foreground "black" :background "yellow")) (((class color) (min-colors 8) (background dark)) (:foreground "white" :background "blue")) (((type tty) (class mono)) (:inverse-video t)) (t (:background "gray"))))
 '(next-error ((t (:inherit (region)))))
 '(query-replace ((t (:inherit (isearch))))))

(provide-theme 'Graham Modified)
