(deftheme pure-inverted
  "Created 2020-11-05.")

(custom-theme-set-faces
 'pure-inverted
 '(cursor ((t (:background "white"))))
 '(fixed-pitch ((t (:family "Monospace"))))
 '(escape-glyph ((t (:background "black" :foreground "white"))))
 '(homoglyph ((t (:foreground "white"))))
 '(minibuffer-prompt ((t (:foreground "white"))))
 '(shadow ((t (:foreground "gray"))))
 '(secondary-selection ((t (:extend t :background "black"))))
 '(trailing-whitespace ((((class color) (background light)) (:background "red1")) (((class color) (background dark)) (:background "red1")) (t (:inverse-video t))))
 '(font-lock-comment-delimiter-face ((t (:slant italic :foreground "#349a3f"))))
 '(font-lock-comment-face ((t (:slant italic :foreground "#349a3f"))))
 '(font-lock-constant-face ((t (:foreground "white"))))
 '(font-lock-doc-face ((t (:foreground "white"))))
 '(font-lock-function-name-face ((t (:foreground "white"))))
 '(font-lock-keyword-face ((t (:foreground "white"))))
 '(font-lock-preprocessor-face ((t (:foreground "white"))))
 '(font-lock-string-face ((t (:foreground "white"))))
 '(font-lock-type-face ((t (:foreground "white"))))
 '(font-lock-variable-name-face ((t (:foreground "white"))))
 '(font-lock-warning-face ((t (:foreground "#FFFFFF"))))
 '(button ((t (:inherit (link)))))
 '(link ((t (:underline (:color foreground-color :style line) :foreground "white"))))
 '(link-visited ((t (:foreground "magenta4" :inherit (link)))))
 '(fringe ((t (:background "#232323"))))
 '(header-line ((t (:inherit mode-line :background "grey20" :foreground "grey90" :box nil))))
 '(tooltip ((t (:inherit variable-pitch :background "systeminfowindow" :foreground "systeminfotext"))))
 '(mode-line ((t (:background "gray10" :foreground "white"))))
 '(mode-line-buffer-id ((t (:weight bold))))
 '(mode-line-emphasis ((t (:weight bold))))
 '(mode-line-highlight ((t nil)))
 '(mode-line-inactive ((t (:foreground "#BCBCBC" :background "black"))))
 '(isearch ((t (:background "#000000" :foreground "gray90"))))
 '(isearch-fail ((t (:foreground "#FFFFFF" :background "#333333"))))
 '(lazy-highlight ((t (:foreground "gray10" :background "#000000"))))
 '(match ((t (:background "white"))))
 '(next-error ((t (:inherit region))))
 '(query-replace ((t (:inherit isearch))))
 '(default ((t (:inherit nil :extend nil :stipple nil :background "black" :foreground "LightSteelBlue2" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 120 :width normal :foundry "outline" :family "Consolas")))))

(provide-theme 'pure-inverted)
