(deftheme waher-improved
  "Created 2022-06-20.")

(custom-theme-set-faces
 'waher-improved
 '(default ((t (:family "Liberation Mono" :foundry "outline" :width normal :height 102 :weight normal :slant normal :underline nil :overline nil :extend nil :strike-through nil :box nil :inverse-video nil :foreground "#CEDBE7" :background "#000000" :stipple nil :inherit nil))))
 '(cursor ((t (:background "#f8f8f2"))))
 '(fixed-pitch ((t (:family "Monospace"))))
 '(variable-pitch ((((type w32)) (:foundry "outline" :family "Arial")) (t (:family "Sans Serif"))))
 '(escape-glyph ((((background dark)) (:foreground "cyan")) (((type pc)) (:foreground "magenta")) (t (:foreground "brown"))))
 '(homoglyph ((((background dark)) (:foreground "cyan")) (((type pc)) (:foreground "magenta")) (t (:foreground "brown"))))
 '(minibuffer-prompt ((t (:foreground "#3090DE"))))
 '(highlight ((t (:background "gray20"))))
 '(region ((t (:extend t :background "#49483E"))))
 '(shadow ((((class color grayscale) (min-colors 88) (background light)) (:foreground "grey50")) (((class color grayscale) (min-colors 88) (background dark)) (:foreground "grey70")) (((class color) (min-colors 8) (background light)) (:foreground "green")) (((class color) (min-colors 8) (background dark)) (:foreground "yellow"))))
 '(secondary-selection ((((class color) (min-colors 88) (background light)) (:extend t :background "yellow1")) (((class color) (min-colors 88) (background dark)) (:extend t :background "SkyBlue4")) (((class color) (min-colors 16) (background light)) (:extend t :background "yellow")) (((class color) (min-colors 16) (background dark)) (:extend t :background "SkyBlue4")) (((class color) (min-colors 8)) (:extend t :foreground "black" :background "cyan")) (t (:inverse-video t))))
 '(trailing-whitespace ((t (:foreground "#3B3A32"))))
 '(font-lock-builtin-face ((t (:foreground "#DEC77B"))))
 '(font-lock-comment-delimiter-face ((t (:foreground "#6F8F6F"))))
 '(font-lock-comment-face ((t (:foreground "#7F9F7F"))))
 '(font-lock-constant-face ((t (:foreground "#DEC77B"))))
 '(font-lock-doc-face ((t (:foreground "#7F9F7F"))))
 '(font-lock-function-name-face ((t (:foreground "#D65921"))))
 '(font-lock-keyword-face ((t (:foreground "#DEC77B"))))
 '(font-lock-negation-char-face ((t (:foreground "#F92F72"))))
 '(font-lock-preprocessor-face ((t (:foreground "#EC9A41"))))
 '(font-lock-regexp-grouping-backslash ((t (:foreground "#DF6300"))))
 '(font-lock-regexp-grouping-construct ((t (:foreground "#DEC777"))))
 '(font-lock-string-face ((t (:foreground "#8CBED6"))))
 '(font-lock-type-face ((t (:foreground "#607060"))))
 '(font-lock-variable-name-face ((t (:foreground "#EFA252"))))
 '(font-lock-warning-face ((t (:foreground "#F92672"))))
 '(button ((t (:inherit (link)))))
 '(link ((((class color) (min-colors 88) (background light)) (:underline (:color foreground-color :style line) :foreground "RoyalBlue3")) (((class color) (background light)) (:underline (:color foreground-color :style line) :foreground "blue")) (((class color) (min-colors 88) (background dark)) (:underline (:color foreground-color :style line) :foreground "cyan1")) (((class color) (background dark)) (:underline (:color foreground-color :style line) :foreground "cyan")) (t (:inherit (underline)))))
 '(link-visited ((default (:inherit (link))) (((class color) (background light)) (:foreground "magenta4")) (((class color) (background dark)) (:foreground "violet"))))
 '(fringe ((t (:background "#292A24"))))
 '(header-line ((default (:inherit (mode-line))) (((type tty)) (:underline (:color foreground-color :style line) :inverse-video nil)) (((class color grayscale) (background light)) (:box nil :foreground "grey20" :background "grey90")) (((class color grayscale) (background dark)) (:box nil :foreground "grey90" :background "grey20")) (((class mono) (background light)) (:underline (:color foreground-color :style line) :box nil :inverse-video nil :foreground "black" :background "white")) (((class mono) (background dark)) (:underline (:color foreground-color :style line) :box nil :inverse-video nil :foreground "white" :background "black"))))
 '(tooltip ((t (:foreground "systeminfotext" :background "systeminfowindow" :inherit (variable-pitch)))))
 '(mode-line ((t (:foreground "#CEDBE7" :background "#222222"))))
 '(mode-line-buffer-id ((t (:weight bold))))
 '(mode-line-emphasis ((t (:foreground "#CDEBF7"))))
 '(mode-line-highlight ((t (:foreground "#CDEBF7"))))
 '(mode-line-inactive ((t (:foreground "#4E4D4A" :background "#292423"))))
 '(isearch ((t (:foreground "#000000" :background "#FFE792"))))
 '(isearch-fail ((((class color) (min-colors 88) (background light)) (:background "RosyBrown1")) (((class color) (min-colors 88) (background dark)) (:background "red4")) (((class color) (min-colors 16)) (:background "red")) (((class color) (min-colors 8)) (:background "red")) (((class color grayscale)) (:foreground "grey")) (t (:inverse-video t))))
 '(lazy-highlight ((((class color) (min-colors 88) (background light)) (:background "paleturquoise")) (((class color) (min-colors 88) (background dark)) (:background "paleturquoise4")) (((class color) (min-colors 16)) (:background "turquoise3")) (((class color) (min-colors 8)) (:background "turquoise3")) (t (:underline (:color foreground-color :style line)))))
 '(match ((((class color) (min-colors 88) (background light)) (:background "khaki1")) (((class color) (min-colors 88) (background dark)) (:background "RoyalBlue3")) (((class color) (min-colors 8) (background light)) (:foreground "black" :background "yellow")) (((class color) (min-colors 8) (background dark)) (:foreground "white" :background "blue")) (((type tty) (class mono)) (:inverse-video t)) (t (:background "gray"))))
 '(next-error ((t (:inherit (region)))))
 '(query-replace ((t (:inherit (isearch))))))

(provide-theme 'waher-improved)
